import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import { Provider } from "@components/ui/provider"
import "./globals.css";
import LayoutSplitter from "@components/LayoutSplitter";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${dmSans.variable} antialiased`}
      >
        <Provider>
          <LayoutSplitter>
            {children}
          </LayoutSplitter>
        </Provider>
      </body>
    </html>
  );
}
